"""Generate self-contained HTML incident reports with inline CSS."""
import os
from podautopsy.models import PostMortemReport, FailureType
from podautopsy.analyzer.timeline import build_timeline
 
FAILURE_BADGE_COLORS = {
    FailureType.OOM_KILLED: '#e74c3c',
    FailureType.CRASH_LOOP: '#f39c12',
    FailureType.EVICTED:    '#9b59b6',
    FailureType.IMAGE_PULL: '#e67e22',
    FailureType.PENDING:    '#3498db',
    FailureType.COMPLETED:  '#27ae60',
    FailureType.UNKNOWN:    '#95a5a6',
}
 
 
def save_html(report: PostMortemReport) -> str:
    content = _render_html(report)
    ts = report.generated_at.strftime('%Y%m%d_%H%M%S')
    filename = f'postmortem_{report.pod_name}_{ts}.html'
    with open(filename, 'w') as f:
        f.write(content)
    return os.path.abspath(filename)
 
 
def _render_html(report: PostMortemReport) -> str:
    color = FAILURE_BADGE_COLORS.get(report.failure_type, '#95a5a6')
    timeline_rows = ''
    for ev in build_timeline(report.events):
        row_cls = 'warning' if ev['type'] == 'Warning' else 'normal'
        timeline_rows += f'''
        <tr class="{row_cls}">
          <td>{ev["timestamp"]}</td>
          <td><span class="badge">{ev["type"]}</span></td>
          <td><strong>{ev["reason"]}</strong></td>
          <td>{ev["message"][:150]}</td>
          <td>{ev["count"]}</td>
        </tr>'''
 
    container_rows = ''
    for c in report.containers:
        state_cls = 'ok' if c.state == 'running' else 'fail'
        container_rows += f'''
        <tr>
          <td><code>{c.name}</code></td>
          <td class="{state_cls}">{c.state}</td>
          <td>{c.reason or '-'}</td>
          <td>{c.exit_code if c.exit_code is not None else '-'}</td>
          <td class="{'fail' if c.restart_count > 2 else ''}">{c.restart_count}</td>
          <td>{"✓" if c.ready else "✗"}</td>
        </tr>'''
    prev_logs_html = '<pre>' + '\n'.join(report.previous_logs[-100:]) + '</pre>' if report.previous_logs else ''
    ai_section = f'<div class="ai-box"><h2>🤖 AI Root Cause Analysis <small>({report.ai_model})</small></h2><p>{report.ai_analysis}</p></div>' if report.ai_analysis else ''
 
    return f'''<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<title>PodAutopsy -{report.pod_name}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background: #0f0f1a; color: #e0e0e0; margin: 0; padding: 20px; }}
  .header {{ background: #1a1a2e; border-left: 6px solid {color};
    padding: 24px; border-radius: 8px; margin-bottom: 24px; }}
  .header h1 {{ margin: 0; font-size: 2em; color: #fff; }}
  .badge {{ background: {color}; color: #fff; padding: 4px 12px;
    border-radius: 20px; font-size: 0.85em; font-weight: bold; }}
  .card {{ background: #16213e; border-radius: 8px; padding: 20px;
    margin-bottom: 20px; border: 1px solid #2a2a4a; }}
  table {{ width: 100%; border-collapse: collapse; }}
  th {{ background: #1e3a5f; color: #88c4f0; padding: 10px; text-align: left; }}
  td {{ padding: 8px 10px; border-bottom: 1px solid #2a2a4a; }}
  tr.warning td {{ border-left: 3px solid #f39c12; }}
  .ok {{ color: #27ae60; }} .fail {{ color: #e74c3c; }}
  pre {{ background: #1e1e1e; padding: 16px; border-radius: 6px;
    overflow-x: auto; font-size: 0.85em; color: #d4d4d4; }}
  .fix-box {{ background: #1a2f1a; border: 1px solid #27ae60;
    border-radius: 6px; padding: 16px; margin-top: 12px; }}
  .ai-box {{ background: #2d1b4e; border: 1px solid #8e44ad;
    border-radius: 8px; padding: 20px; margin-top: 20px; }}
  code {{ background: #2a2a4a; padding: 2px 6px; border-radius: 3px; }}
</style></head><body>
<div class="header">
  <h1>PodAutopsy - Incident Report</h1>
  <p><span class="badge">{report.failure_type.value}</span></p>
  <p><strong>Pod:</strong> {report.pod_name} &nbsp;|&nbsp;
     <strong>Namespace:</strong> {report.namespace} &nbsp;|&nbsp;
     <strong>Node:</strong> {report.node_name or 'N/A'} &nbsp;|&nbsp;
     <strong>Generated:</strong> {report.generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
</div>
<div class="card">
  <h2>Root Cause</h2>
  <p>{report.failure_summary}</p>
  <div class="fix-box"><strong>💡 Suggested Fix:</strong><br>{report.suggested_fix}</div>
</div>
<div class="card"><h2>Container States</h2>
  <table><thead><tr><th>Container</th><th>State</th><th>Reason</th>
    <th>Exit Code</th><th>Restarts</th><th>Ready</th></tr></thead>
  <tbody>{container_rows}</tbody></table></div>
<div class="card"><h2>Event Timeline</h2>
  <table><thead><tr><th>Time</th><th>Type</th><th>Reason</th>
    <th>Message</th><th>Count</th></tr></thead>
  <tbody>{timeline_rows}</tbody></table></div>
{f'<div class="card"><h2>Previous Container Logs</h2>{prev_logs_html}</div>' if prev_logs_html else ''}
{ai_section}
<p style="color:#555;text-align:center;margin-top:40px">
  Generated by <strong>PodAutopsy</strong></p>
</body></html>'''
