"""Generate Markdown incident reports."""
import os
from podautopsy.models import PostMortemReport
from podautopsy.analyzer.timeline import build_timeline
 
 
def save_markdown(report: PostMortemReport) -> str:
    """Save markdown report to file, return file path."""
    content = _render(report)
    ts = report.generated_at.strftime('%Y%m%d_%H%M%S')
    filename = f'postmortem_{report.pod_name}_{ts}.md'
    with open(filename, 'w') as f:
        f.write(content)
    return os.path.abspath(filename)
 
 
def _render(report: PostMortemReport) -> str:
    lines = []
    lines.append(f'# Incident Report: {report.pod_name}')
    lines.append('')
    lines.append(f'**Generated:** {report.generated_at.strftime("%Y-%m-%d %H:%M:%S UTC")}')
    lines.append(f'**Namespace:** `{report.namespace}`')
    lines.append(f'**Node:** `{report.node_name or "N/A"}`')
    lines.append('')
    lines.append('---')
    lines.append('')
    lines.append(f'## ⚠️  Failure Type: {report.failure_type.value}')
    lines.append('')
    lines.append(f'> {report.failure_summary}')
    lines.append('')
    lines.append(f'**Suggested Fix:** {report.suggested_fix}')
    lines.append('')
 
    # Containers
    lines.append('## Container States')
    lines.append('')
    lines.append('| Container | State | Reason | Exit Code | Restarts | Ready |')
    lines.append('|-----------|-------|--------|-----------|----------|-------|')
    for c in report.containers:
        lines.append(f'| `{c.name}` | {c.state} | {c.reason or "-"} | {c.exit_code or "-"} | {c.restart_count} | {"✓" if c.ready else "✗"} |')
    lines.append('')
 
    # Node conditions
    pressure = [c for c in report.node_conditions if c.status == 'True' and c.type != 'Ready']
    if pressure:
        lines.append('## ⚡ Node Pressure')
        lines.append('')
        for c in pressure:
            lines.append(f'- **{c.type}**: {c.message}')
        lines.append('')
 
    # Events
    if report.events:
        lines.append('## Event Timeline')
        lines.append('')
        lines.append('| Time | Type | Reason | Message |')
        lines.append('|------|------|--------|---------|')
        for ev in build_timeline(report.events):
            msg = ev['message'].replace('|', '\\|')[:100]
            lines.append(f'| {ev["timestamp"]} | {ev["type"]} | {ev["reason"]} | {msg} |')
        lines.append('')
 
    # Previous logs (the gold — crash logs)
    if report.previous_logs:
        lines.append('## Previous Container Logs (pre-crash)')
        lines.append('')
        lines.append('```')
        lines.extend(report.previous_logs[-100:])
        lines.append('```')
        lines.append('')
 
    # AI analysis
    if report.ai_analysis:
        lines.append(f'## 🤖 AI Root Cause Analysis ({report.ai_model})')
        lines.append('')
        lines.append(report.ai_analysis)
        lines.append('')
 
    lines.append('---')
    lines.append('*Generated by [PodAutopsy](https://github.com/YOUR_USERNAME/podautopsy)*')
    return '\n'.join(lines)
